### ISSUE TITLE
How do I save all the submaps as multiple PGM images?

### ISSUE THREAD

**Issue by woshidaye** [cartographer-project/cartographer_ros#1096]
I use submap_query service to save the submap cells can not be reduced to a submap two-dimensional matrix. I want to save each submap as a PGM image or save the two-dimensional matrix(0~255).

**Comment by MichaelGrupp** [comment]
This is something you would need to program yourself in a forked repository. But you can have a look at what the `pbstream_to_ros_map` tool does and change it to write an image for every submap slice instead of a combined image. https://github.com/cartographer-project/cartographer_ros/blob/1c9274ffeeb0253f0894b8d89f4fae5121ac165e/cartographer_ros/cartographer_ros/pbstream_to_ros_map_main.cc#L44
