### ISSUE TITLE
Non-sorted data added to queue: '(1, points2)'

### ISSUE THREAD

**Issue by alfred31** [cartographer-project/cartographer_ros#1123]
Hi,
I have a rotary laser in my robot, and I am building poinclouds from the scan messages. The thingis thath I am able to assemble a pointcloud, but when I try to pass it to cartographer node is killed, and I got the error above (Non-sorted data added to queue: '(1, points2)').

Can anyone tell me why I am getting this issue?

Thanks a lot for your help !

Kind Regards

**Comment by Sanderi44** [comment]
Hi Alfred,
This error occurs because the latest data timestamp is less than the previous timestamp in the queue.  You should check that the timestamps of your data are consistent. Also is could be that simulation time is messing with your timestamps.  You should check whether this line is in your launch file and see if turning it off fixes the problem: 
`<param name="/use_sim_time" value="true" /> `
