### ISSUE TITLE
Serialization vs sensor time

### ISSUE THREAD

**Issue by morsingher** [cartographer-project/cartographer_ros#1399]
Dear Cartographer community, 

I'm opening this issue to clarify a conceptual doubt that seems to be common to several discussions here on Github. It happens frequently that the output of `cartographer_rosbag_validate` includes one or more lines complaining about the mismatch between the serialization time and the sensor time, such as the screenshot attached below:

![screen](https://user-images.githubusercontent.com/36917382/67089587-4c650780-f1a8-11e9-99e6-31b0bc7f87d7.png)

I have 3 main questions related to this:

1) On a conceptual level, why would this happen and what do these serialization/sensor time refer to? Is it related to a bad configuration of the robot sensors? 
2) According to severl discussions I read here, this might be an issue for visualization but not for Cartographer itself. Can you confirm it? Will this affect the quality of mapping and localization?
3) Why this line is shown sometimes as an error and other times as a warning, even if it happens to be the same thing?

I didn't include my bag or any other detail because it's not related to a specific application but it's rather a more general question. Thank you very much for your help,

Marco.

**Comment by ojura** [comment]
Serialization time is the time when the message arrives to the Cartographer node or the rosbag record node. It's not of big importance since Cartographer deterministically processes all data sorted by sensor time, so it does not really matter when the data exactly arrived as long as the sensor time in the message header is correct. For realtime operation where you're using Cartographer for steering a vehicle, big delays could be problematic, but for making maps, serialization time is not really important.
