### ISSUE TITLE
 localisation with a pgm map

### ISSUE THREAD

**Issue by JinzeDing** [cartographer-project/cartographer_ros#1422]
I am a fresher in cartographer. In my project, I wanna use the cartographer instead of amcl to complete the localization task in the navigation. I have the accurate map in the pgm format. How could I load the pgm map in the cartographer to do the localization?  Or, is there any function like the pb_stream to ros_map that  could directly convert rosmap (pgm+yaml) to pbstream?

**Comment by Tutorgaming** [comment]
I think you need to have a look at Cartographer's Algorithm first. It is the Graph-based Localization with the sub-map inside. If you compare the model of both "amcl" which is occupancy grid localization and "cartographer" You will found that only the image is not enough to do the localization. It must have the pose graph, sub-maps and many things to be prepared first. :)

**Comment by barzelshir** [comment]
> I think you need to have a look at Cartographer's Algorithm first. It is the Graph-based Localization with the sub-map inside. If you compare the model of both "amcl" which is occupancy grid localization and "cartographer" You will found that only the image is not enough to do the localization. It must have the pose graph, sub-maps and many things to be prepared first. :)

Maybe it's possible by creating one sub map which is the occupancy values of the loaded pgm file and create sub maps on top of it? without any new trajectory nodes, what do you think? can it work?

**Comment by MichaelGrupp** [comment]
There is currently no direct conversion from a map image to a Cartographer map available in this repository. And it wouldn't be trivial to do.

**Comment by MigVega** [comment]
Hi all,

Now you can use the [Ogm2Pgbm package](https://github.com/MigVega/Ogm2Pgbm) to do the conversion from` .pgm` to Pose graph based map in `.pbtream` format !

If haven't compiled cartographer already, you can follow the provided instructions in the [readme](https://github.com/MigVega/Ogm2Pgbm). It will allow you to compile everything in one isolated container.

Otherwise you can also use the [package](https://github.com/MigVega/Ogm2Pgbm/tree/main/ogm2pgbm) as a normal separated catkin package.

Have fun, and enjoy the power of graph-based localization! :D
