### ISSUE TITLE
Run cartographer on robot

### ISSUE THREAD

**Issue by vaibhavviswanathan** [cartographer-project/cartographer_ros#833]
With the demos, I see how to run cartographer on a collected bagfile. How do I run it in real-time and use it for localization?

This consists of a few questions:

1. How do I publish the pose of the robot wrt the map?
2. How do I save the map for future localization?
3. In the future, how do I localize within that map (in ROS)?

**Comment by cschuet** [comment]
> 1. How do I publish the pose of the robot wrt the map?
That's automatically done as part of the TF topic Cartographer publishes. If you set provide_odom = True Cartographer publish two transforms: map_frame => odom_frame and odom_frame => published_frame, and otherwise only map_frame => published_frame
> 2. How do I save the map for future localization?
Either do the mapping by running the online node and use the ROS service calls finish_trajectory and write_state or record a bag and run something along the lines of 
```
roslaunch cartographer_ros offline_backpack_2d.launch bag_filenames:=${HOME}/Downloads/b2-2016-04-05-14-44-52.bag
```
which gives a pbstream our map file format.

> 3. In the future, how do I localize within that map (in ROS)?
When you start the cartographer_node pass the above pbstream as the load_state_filename parameter
