### ISSUE TITLE
Help needed for obtaining cleaner map with well defined walls

### ISSUE THREAD

**Issue by esonetec** [cartographer-project/cartographer_ros#887]
Hi,

I would like to ask if it is possible to help me finding out the best parameters for cartographer when using an a handheld laser and an IMU. I have been trying my current configuration in several environments and the results are typically good, but recently I faced some issues. 

![image](https://user-images.githubusercontent.com/1550665/40731134-b21f9592-6430-11e8-9754-bccddce84c30.png)

![image](https://user-images.githubusercontent.com/1550665/40731158-c182b3ac-6430-11e8-9f5f-e9fba56f0d49.png)

Above you can see some examples. I would like to obtain a cleaner map with well defined walls.

I attached the rosbag files, our launch file and config file: https://drive.google.com/file/d/1Ly53w_6R6XfvVDy8jJjgwo-si8EiaB7K/view?usp=sharing

Thanks in advance.

**Comment by gaschler** [comment]
Generally, please also post cartographer_rosbag_validate results. In most cases issues in the input data can be found without replaying bag files.

I took a quick look at the lua file.

`TRAJECTORY_BUILDER_2D.missing_data_ray_length = 0`

Why do ignore rays without reflections?

`TRAJECTORY_BUILDER_2D.submaps.num_range_data = 150`

How many seconds of laser scans is 150 messages? (5-20 s would be fine.)

`TRAJECTORY_BUILDER_2D.use_imu_data = true`

Have you tried without? With IMU, your urdf transform from IMU to laser scanner, especially the rotation, *must* be correct. Since you didn't upload one, I'm afraid you use the default one from backpack_2d.

As always, please take a look at the tuning guide and first run without global SLAM. Global SLAM would only hide issues, especially in your case where there is drift.
Hope that helps.
